# Generated by Django 5.1.1 on 2025-01-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3app', '0003_failedloginattempt_alter_watch_options_promotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='updatedAt',
            field=models.DateField(auto_now=True),
        ),
    ]
