# Generated by Django 5.1.1 on 2024-12-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cod',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_confirmat',
            field=models.BooleanField(default=False),
        ),
    ]
